# 开发环境配置

app_name = "hook_wallet_api_dev"

[server]
host = "127.0.0.1"
port = 3000

[tracing]
level = "info"
with_target = true
with_thread_ids = true
with_thread_names = true
with_file = true
with_line_number = true
pretty = true
json = false
with_ansi = true


[chains]
[chains.solana]
url = "https://solana-rpc.publicnode.com"

[chains.ethereum]
url = "https://eth-pokt.nodies.app"
node = "Archival"

[chains.smartchain]
url = "https://bsc-dataseed1.bnbchain.org"

[chains.polygon]
url = "https://polygon.llamarpc.com"

[chains.arbitrum]
url = "https://arb1.arbitrum.io/rpc"


[ankr]
[ankr.key]
secret = "8ce1b2802b07e321a9e41e6ddfda192ed7437fe75ea0238dd9231eb8513f03f5"

[trongrid]
[trongrid.key]
secret = ""