# 开发环境配置

app_name = "hook_wallet_api_dev"

[server]
host = "127.0.0.1"
port = 3000

[tracing]
level = "debug"
with_target = true
with_thread_ids = true
with_thread_names = true
with_file = true
with_line_number = true
pretty = true
json = false
with_ansi = true
