# 生产环境配置

app_name = "hook_wallet_api_prod"

[server]
host = "0.0.0.0"
port = 8080

[tracing]
level = "info"
with_target = true
with_thread_ids = false
with_thread_names = false
with_file = false
with_line_number = false
pretty = false
json = true
with_ansi = false


[chains]
[chains.solana]
url = "https://solana-rpc.publicnode.com"

[chains.ethereum]
url = "https://eth-pokt.nodies.app"
node = "Archival"

[chains.smartchain]
url = "https://bsc-dataseed1.bnbchain.org"

[chains.polygon]
url = "https://polygon.llamarpc.com"

[chains.arbitrum]
url = "https://arb1.arbitrum.io/rpc"


[ankr]
[ankr.key]
secret = "8ce1b2802b07e321a9e41e6ddfda192ed7437fe75ea0238dd9231eb8513f03f5"

[trongrid]
[trongrid.key]
secret = ""