# 生产环境配置

app_name = "hook_wallet_api_prod"

[server]
host = "0.0.0.0"
port = 8080

[tracing]
level = "info"
with_target = true
with_thread_ids = false
with_thread_names = false
with_file = false
with_line_number = false
pretty = false
json = true
with_ansi = false
